# 用户id和组id/User id and group id
agh_uid=root
agh_gid=net_raw

# 时区/Time zone
# 请设置合法的时区格式，否则会回退到UTC时间/
time_zone=

# 运行日志/Running log
# 输出文件/Output file: /data/adb/mudules/AdSentry/run.log
enable_log=false

# 重定向端口/Redirect port
redirect_port=35353

# 配置iptables/Configure iptables
configure_iptables=true

# IPv6 DNS请求丢弃/IPv6 DNS request drop
drop_ipv6_dns=true

# 模块路径/Module path
readonly MOD_DIR="/data/adb/modules/AdSentry"